apiVersion: v1
kind: Service
metadata:
  name: devops-demo-frontend-internal
  namespace: demo
spec:
  selector:
    app: devops-demo-frontend
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devops-demo-frontend
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo-frontend
  template:
    metadata:
      labels:
        app: devops-demo-frontend
    spec:
      containers:
      - name: devops-demo-frontend
        image: mycluster.icp:8500/demo/devops-demo-frontend:0.1
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_HOST
          value: "devops-demo-backend-internal"
        - name: BACKEND_PORT
          value: 9080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: devops-demo-frontend-external
 namespace: demo
spec:
  rules:
  - http:
      paths:
      - path: /demo
        backend:
         serviceName: devops-demo-frontend-internal
         servicePort: 8080